// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// OwnerColor is one of Nestorage's five owner palette keys, matching the
// Tailwind owner-color token infix (owner-<key>-{solid,tint,fg} in
// web/static/css/input.css). It is typed rather than a bare string (compare
// Nestova's MemberColor) so an invalid value can only ever reach a template
// through ParseOwnerColor's documented fallback, never propagated silently.
type OwnerColor string

// The five owner palette keys. OwnerShared is "Family" — a bin owned by the
// household rather than a person.
const (
	OwnerIndigo OwnerColor = "indigo"
	OwnerSteel  OwnerColor = "steel"
	OwnerTeal   OwnerColor = "teal"
	OwnerPeri   OwnerColor = "peri"
	OwnerShared OwnerColor = "shared"
)

// String returns the Tailwind class infix for c.
func (c OwnerColor) String() string {
	return string(c)
}

// ParseOwnerColor parses s into an OwnerColor, falling back to OwnerShared
// for an unrecognized value so a bad input can never emit a class outside
// the @source inline safelist in web/static/css/input.css.
func ParseOwnerColor(s string) OwnerColor {
	switch OwnerColor(s) {
	case OwnerIndigo, OwnerSteel, OwnerTeal, OwnerPeri, OwnerShared:
		return OwnerColor(s)
	default:
		return OwnerShared
	}
}

// OwnerView is the view-layer model for an owner avatar/chip: a display
// name, avatar initials, and a color. It deliberately is not a domain type —
// Nestorage's identity model does not land until Sprint 3, and the shell has
// to render before then.
type OwnerView struct {
	Name     string
	Initials string
	Color    OwnerColor
}

// OwnerAvatar renders o's initials on a tinted circle, sized for touch. The
// accessible name identifies the owner by name ("Owned by Maya") rather than
// exposing the bare initial to assistive tech.
func OwnerAvatar(o OwnerView) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{"flex h-[30px] w-[30px] flex-none items-center justify-center rounded-full text-sm font-bold", ownerTintClasses(o.Color)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<span class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/owner.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" aria-label=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("Owned by " + o.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/owner.templ`, Line: 53, Col: 35}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" title=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(o.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/owner.templ`, Line: 54, Col: 16}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"><span aria-hidden=\"true\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(o.Initials)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/owner.templ`, Line: 56, Col: 39}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</span></span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ownerTintClasses returns an owner's tint background and matching
// foreground together, so a tint from one palette key can never be paired
// with a foreground from another — that pairing guarantee is what makes it
// structurally impossible, not just discouraged.
func ownerTintClasses(c OwnerColor) string {
	return "bg-owner-" + c.String() + "-tint text-owner-" + c.String() + "-fg"
}

// ownerSolidClasses returns an owner's solid background paired with a white
// foreground, for chips that sit on the solid fill rather than the tint
// (e.g. the sidebar owner toggle).
func ownerSolidClasses(c OwnerColor) string {
	return "bg-owner-" + c.String() + "-solid text-white"
}

var _ = templruntime.GeneratedTemplate
